### ISSUE TITLE
How to visualize the hair model with colored strands

### ISSUE THREAD

**Issue by MrTornado24** [mxxo/hair-data-converter#1]
Hi, thanks for your code! I run it and visualize the .obj file on meshlab, as shown below.
![image](https://user-images.githubusercontent.com/45503891/176846378-36f72a42-99c7-4050-bd67-8d4b86478719.png)

I wonder how to get the colored strands like this:
![image](https://user-images.githubusercontent.com/45503891/176846521-0a95a6ee-8a51-4b8e-91a7-127269bd2785.png)

**Comment by mxxo** [comment]
Hello, I don't have `meshlab` installed, but I would try adding `rgb` colors at the end of each vertex line in `hair2obj`:
https://github.com/mxxo/hair-data-converter/blob/277f146cc51f620c7470113c7704c8d9634cee0a/src/hair2obj.cpp#L54-L60

The `Hair` struct does have a `colors` field, but I don't think it gets populated during reading, and likely is only intended for use through the `color` method to set a global hair color.

https://github.com/mxxo/hair-data-converter/blob/277f146cc51f620c7470113c7704c8d9634cee0a/include/Hair.h#L17-L29

To get the effect shown in the second picture, I think you will have to come up with some coloring logic for each strand to accomplish this.

**Comment by MrTornado24** [comment]
Thanks very much!
